<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="Keywords" content="Proof, Segurança informação, Business Analitcs" />
        <meta name="Description" content="Proof" />
        
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/principal.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/menu.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/tabelas.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/style.css" />
        <!-- <link rel="stylesheet" type="text/css" href="<?php // echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/testes.css" /> -->
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/login.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/only_j3.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/formularios.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/template_j3.css" />
	
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery-2.1.4.js"></script>
        
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/jq-2.1.4,dt-1.10.10,b-1.1.0,b-colvis-1.1.0,cr-1.3.0,r-2.0.0,rr-1.1.0,sc-1.4.0,se-1.1.0/datatables.min.css"/>
		<script type="text/javascript" src="https://cdn.datatables.net/s/dt/jq-2.1.4,dt-1.10.10,b-1.1.0,b-colvis-1.1.0,cr-1.3.0,r-2.0.0,rr-1.1.0,sc-1.4.0,se-1.1.0/datatables.min.js"></script>

		<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery-ui-1.11.4.custom/jquery-ui.css" />        
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery-ui-1.11.4.custom/jquery-ui.js"></script>		
		
        <title>Proof</title>
    </head>
    <body>

        <div id="navwrap">

            <div id="topnav">
                <?php  $objMenu = new Menu();  if ( self::$session->getFromSession('menu') ) { $objMenu->arvoreMenu ( self::$session->getFromSession('menu') ); } ?>
                <span id="infouser">Usuário: <b><?php echo self::$session->getFromSession('full_name'); ?></b> | <a href="<?php echo BASE_URL . 'principal/logout/';?>">Sair</a></span>
            </div>

        </div>

        <div id="conteudo">
            {contents}
        </div>
		<div id="dinamico"></div>
        <div id="rodape">COpS - Centro de Operação de Segurança<br />Copyright &copy; <?php echo Date("Y"); ?></div>
    </body>
</html>