<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <title>COpS - Centro de Operação de Segurança</title>
        <style type='text/css'>
            p {
                 font-family: 'Arial', Garamond, 'Comic Sans'; 
                 font-size: 13px;
             } 
            table.myTable { 
                 border: 1px solid black;
                 border-collapse:collapse; 
             }

            table.myTable td { 
                 font-family: 'Arial', Garamond, 'Comic Sans'; 
                 font-size: 12px; 
                 border:1px solid black;
                 padding:5px; 
             }
        </style>
    </head>
    <body>
    	{contents}
        <p style="margin: 5px;"><br />COpS - Centro de Operação de Segurança<br />Mensagem automática gerada em: <?php echo date('d/m/Y H:i:s')?> UTC</p>
    </body>
</html>