<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/bs/bootstrap.min.css">
    <link href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/font-awesome.min.css" rel="stylesheet">
    <link href='<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/bs/gfont.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/bs/style2.css">
    <script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/bs/jquery.min.js"></script>
    <script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/bs/bootstrap.min.js"></script>
  </head>

  <body>
      {contents}
  </body>
</html>      