<script type="text/javascript">
    $(document).ready(function() {

        $('#listaUsuarios').DataTable({
            "language": {
                "url": "<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/datatables/examples/resources/pt_BR.txt"
            }
        });

        $("#dialog:ui-dialog" ).dialog( "destroy" );
        $( "#dialog" ).dialog({
            autoOpen: false,
            title: 'Informacao de Usuarios',
            height: 470,
            width: 700,
            show: {
              effect: "fade",
              duration: 500
            },
            hide: {
              effect: "fade",
              duration: 500
            }
        });
       
        $("a[id^='script']").click(function(){

            var id_script = $(this).siblings('input#id_script').val();

            $( '#dialog' ).load( "<?php echo BASE_URL.'usuario/consulta/'; ?>" + id_script);
        	$( "#dialog" ).dialog( "open" );
        });

        $("button#cadastro").click(function(){

        	$( '#dialog' ).load( "<?php echo BASE_URL.'usuario/cadastro/'; ?>");
        	$( "#dialog" ).dialog( "open" );
        	
        });

        $("a[id^='edita_']").click(function(){

            var id_script = $(this).siblings('input#id_script').val();

            $( '#dialog' ).load( "<?php echo BASE_URL.'usuario/edita/'; ?>" + id_script);
        	$( "#dialog" ).dialog( "open" );
        });

        $("a[id^='exclui_']").click(function(){

        	var id_script 	= $(this).siblings('input#id_script').val();

        	$( "#confirm" ).html('<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseja realmente excluir?</p>');

        	// Confirmacao de exclusao
            
            $( "#confirm" ).dialog({
            	autoOpen: false,
            	title: 'Excluir registro?',
                resizable: false,
                height:180,
                modal: true,
                buttons: {
                  "Excluir": function() {

    	                $.get( "<?php echo BASE_URL.'usuario/exclui/'; ?>" + id_script );
    	                $( this ).dialog( "close" );
    	                location.reload();
                  },
                  Cancelar: function() {
                    	$( this ).dialog( "close" );
                  }
                },
                show: {
                    effect: "fade",
                    duration: 500
                },
                hide: {
                    effect: "fade",
                    duration: 500
                }
    		});
        	
            $( "#confirm" ).dialog( "open" );
        });

        
    });
</script> 

<div class="registration" style="padding: 10px; margin-bottom: 30px;">
    
    <div style="margin-bottom: 15px;"> 
        <button id="cadastro" class="btn btn-primary">Cadastrar</button>
    </div>

    <table id="listaUsuarios" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
			<tr bgcolor='#AAAAFA'>
				<th width="10%" style="text-align: center;">Login</th>
				<th width="30%" style="text-align: center;">Nome Completo</th>
				<th width="10%" style="text-align: center;">Tipo</th>
                                <th width="10%" style="text-align: center;">Autenticacao</th>
				<th width="10%" style="text-align: center;">Situacao</th>
				<th width="10%" style="text-align: center;">Perfil</th>
				<th width="20%" style="text-align: center;">Opcoes</th>
			</tr>
        </thead>
        <tbody>
            <?php foreach ($usuarios as $usuario): ?>
			<tr>
				<td width="10%" style="text-align: center;"><?php echo $usuario->login; ?></td>
				<td width="30%"><?php echo $usuario->full_name; ?></td>
                                <td width="10%" style="text-align: center;"><?php echo $usuario->description; ?></td>
				<td width="10%" style="text-align: center;"><?php echo $usuario->driver; ?></td>
				<td width="10%" style="text-align: center;"><?php echo ($usuario->status == 'A' ? 'ATIVO' : 'INATIVO'); ?></td>
				<td width="10%" style="text-align: center;"><?php echo $usuario->name_profile; ?></td>
				<td align="center">
					<a id="edita_<?php echo $usuario->id; ?>" href="#">
                    	<img src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>images/icones/24/tool.png" />
                    </a>
                    <a id="exclui_<?php echo $usuario->id; ?>" href="#">
                    	<img src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>images/icones/24/Recycle.png" />
                    </a>
                    <input type="hidden" value="<?php echo $usuario->id; ?>" id="id_script" />
				</td>
			</tr>
			<?php endforeach; ?>
        </tbody>
    </table>

	<div id="dialog"></div>
	<div id="confirm"></div>
</div>