<link href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/sDashboard.css" rel="stylesheet">
<link href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/css/jquery.minitwitter.css" rel="stylesheet">
<link href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/css/gitter/css/jquery.gritter.css" rel="stylesheet"/>

<script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/libs/touchpunch/jquery.ui.touch-punch.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/libs/gitter/jquery.gritter.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/libs/datatables/jquery.dataTables.js"></script>

<!--[if IE]>
<script language="javascript" type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/libs/flotr2/flotr2.ie.min.js"></script>
<![endif]-->
<script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/libs/flotr2/flotr2.js" type="text/javascript"></script>

<script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/jquery-sDashboard.js" type="text/javascript"> </script>
<script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/libs/themeswitcher/jquery.themeswitcher.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/libs/miniTwitter/jquery.minitwitter.js" type="text/javascript"></script>
<!-- <script src="<?php // echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/dashboards/libs/exampleData.js" type="text/javascript"></script> -->

<div>
	<a href="<?php echo BASE_URL.'script/excel/' . $script[0]->cod_alerta; ?>">
		<img style='margin-top: 5px; margin-bottom:5px; float: right;' src='<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>images/icones/excel.png' />
	</a>
</div>
<table id="listaExecucoes" class="table table-striped table-bordered" cellspacing="0" width="100%">
	<tbody>
		<tr>
		<?php $campos = explode (",", $script[0]->tabela_colunas); foreach ($campos as $campo) : if ( !empty( $campo ) ) : ?>
			<th><?php echo strtolower( str_replace('"', '', trim( $campo ) ) );  ?></th>
			<?php endif; endforeach; ?>
		</tr>
		<?php foreach ($registros as $indice => $registro): ?>
		<tr>
			<?php foreach ($campos as $campo) : if ( !empty( $campo ) ) : $campo = str_replace('"', '', trim( $campo ) ); ?>
				<td><?php echo $registro->$campo; ?></td>					
			<?php endif; endforeach; ?>				
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
