<script type="text/javascript">

	$(document).ready(function() {

        $('#listaScripts').DataTable({
            "language": {
                "url": "<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/datatables/examples/resources/pt_BR.txt"
            }
        });
    });
</script> 

<div class="registration" style="padding: 10px; margin-bottom: 30px;">
    
	<table id="listaScripts" class="table table-striped table-bordered" cellspacing="0" width="100%">
		<thead>
			<tr bgcolor='#AAAAFA'>
				<th>Cod Alerta</th>
				<th>Descricao</th>
				<th>Horario Agendado</th>
				<th>Finalizado em</th>
				<th>Erro</th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($problemas as $problema): ?>
			<tr>
				<td align="center"><?php echo $problema->cod_sox; ?></td>
				<td align="center"><?php echo $problema->descricao; ?></td>
				<td align="center"><?php echo $problema->hora; ?></td>
				<td align="center"><?php echo $problema->hora; ?></td>
				<td align="center"><?php echo $problema->erro_num; ?></td>
				<td align="center"><?php echo $problema->qtd_reg; ?></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	
</div>