<script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/rolagem.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/tablesorter.js"></script>
<div style="border: 1px solid blue;">
	<div style="margin-top: 10px; font-size: 18px; text-align: center;">Tela Inicial</div>
	<div></div>
	<div id="cidadesLista"></div>
</div>