<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="Keywords" content="Proof, Segurança informação, Business Analitcs" />
        <meta name="Description" content="Proof" />
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery-ui-1.8.18.custom.min.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/mascara_monetaria.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/mascaras.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery.alerts.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery-ui-1.8.18.custom/js/ui.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery-validation-1.9.0/jquery.validate.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/slimScroll.js"></script>

        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/itaguary.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/ajax.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/validacao_formularios.js"></script>
        <!--<script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery.pagination.js"></script> -->
        <!--<script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/members.js"></script> -->
        <script type="text/javascript" src="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/testes.js"></script>

        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/jquery.alerts.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/principal.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/menu.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/autocomplete.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>js/jquery-ui-1.8.18.custom/css/redmond/jquery-ui-1.8.18.custom.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/tabelas.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/style.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/ui.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/formularios.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/pagination.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/testes.css" />
        <link rel="stylesheet" type="text/css"  href="<?php echo BASE_URL.TEMPLATE_DIR.'/'.$this->template.'/'; ?>css/login.css" />
        <title>Proof</title>
    </head>
    <body>
        <div id="navwrap">
            <div id="topnav">
                <span id="infouser">&nbsp;</span>
            </div>
        </div>
        <div id="conteudo">
            {contents}
        </div>
        <div id="rodape">COpS - Centro de Operação de Segurança<br />Copyright &copy; 2015</div>
    </body>
</html>