<p>Prezados,</p>

<p>As senhas das contas de serviço <b>cc059143</b> e <b>k28902</b> vão expirar em menos de 15 dias. Favor acionar a equipe N2 para efetuar alteração nos locais citados abaixo.</p>

<b>REGRA:</b> <i>Alertar a data de expiração das contas de serviço utilizadas nos scripts do COpS.</i>

<p>A lista a seguir, informa os scripts e locais onde as senhas devem ser alteradas.</p>

<table class='myTable'>
    <tr bgcolor='#DE9494' align='center' style="font-weight: bold;">
        <td colspan=2>Dados Levantados</td>
    </tr>
    <tr align='center' style="font-weight: bold;">
        <td>Scripts Mainframe</td>
		<td>LGWPW01A e LGWPW01B</td>
    </tr>
	<tr>
		<td>DBI_LINK ID 343</td>
		<td>DBI_LINK ID 17</td>												
	</tr>
</table>    